### ISSUE TITLE
login error on Linux (browserType.launch: Browser closed.)

### ISSUE THREAD

**Issue by julianferres** [searleser97/cpbooster#60]
**Please complete the following information:**
cpbooster version: 2.6.4
OS: Ubuntu
Using Vim? : no
Using Neovim? : yes
Terminal Name: alacritty

**Describe the bug**

**Steps To Reproduce it**
1. Run login with any arg: e.g `cp login atcoder`

**Expected behavior**
Some kind of wizard or popup in browser

**Error received**
```
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /home/julian/.cache/ms-playwright/chromium-1005/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-0OQOYi --remote-debugging-pipe --no-startup-window
<launched> pid=305590
[pid=305590] <process did exit: exitCode=null, signal=SIGSEGV>
[pid=305590] starting temporary directories cleanup
=========================== logs ===========================
<launching> /home/julian/.cache/ms-playwright/chromium-1005/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-0OQOYi --remote-debugging-pipe --no-startup-window
<launched> pid=305590
[pid=305590] <process did exit: exitCode=null, signal=SIGSEGV>
[pid=305590] starting temporary directories cleanup
============================================================
    at AtCoder.<anonymous> (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:239:81)
    at step (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:69:23)
    at Object.next (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:50:53)
    at /home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:44:71
    at __awaiter (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:40:12)
    at AtCoder.OnlineJudge.login (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:234:16)
    at Object.login (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/Login/Login.js:27:8)
    at Object.handler (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/index.js:174:37)
    at Object.runCommand (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.<anonymous> (/home/julian/.nvm/versions/node/v17.4.0/lib/node_modules/cpbooster/dist/src/index.js:214:3) {
  name: 'Error'
}

Node.js v17.4.0
```

**Comment by searleser97** [comment]
wow! never happened to me before, probably try with a lower version of Node? I see you are currently using 17.4.0

**Comment by julianferres** [comment]
Changed to version `v14.19.3` and similar error arose, but after removing the ms-playwright cache and reinstalling it, the error dissapeared :smiley:

It worked in both `v14.19.3` and `v17.4.0.`

```
rm -rf .cache/ms-playwright 
npx playwright install 
```
