### ISSUE TITLE
Unable to login.

### ISSUE THREAD

**Issue by fhvirus** [searleser97/cpbooster#96]
**Please complete the following information:**
cpbooster version: 2.6.5
OS: Ubuntu 23.04
Using Vim? : no
Using Neovim? : no
Terminal Name: Konsole

**Describe the bug**
When using login command `cpb l atcoder`, it gives the error provided in Screenshots section.

**Steps To Reproduce it**
1. Install nvm, nodejs and npm by following the instructions on nvm's website.
2. `npm install cpbooster -g`
3. `cpb l atcoder` or `cpb l codeforces` gives the same error.

**Screenshots**
```
$ cpb l atcoder
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserContext.newPage: Browser closed.
==================== Browser output: ====================
<launching> /home/lemon/.cache/ms-playwright/chromium-1076/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-jjFs9b --remote-debugging-pipe --no-startup-window
<launched> pid=484869
[pid=484869][err] 
[pid=484869][err] (chrome:484869): Gtk-WARNING **: 10:16:14.747: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name
[pid=484869][err] 
[pid=484869][err] (chrome:484869): Gtk-WARNING **: 10:16:14.747: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
[pid=484869][err] [484869:484869:0904/101614.821117:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.
[pid=484869][err] [0904/101615.014686:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=484869][err] [0904/101615.014908:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=484869][err] [0904/101615.014959:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=484869][err] [0904/101615.015012:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=484869][err] Received signal 11 SEGV_MAPERR 000000000148
[pid=484869][err] #0 0x559fce7d0842 base::debug::CollectStackTrace()
[pid=484869][err] #1 0x559fce7bde23 base::debug::StackTrace::StackTrace()
[pid=484869][err] #2 0x559fce7d02d1 base::debug::(anonymous namespace)::StackDumpSignalHandler()
[pid=484869][err] #3 0x7fadc723c4b0 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x3c4af)
[pid=484869][err] #4 0x559fca518710 base::ObserverList<>::AddObserver()
[pid=484869][err] #5 0x559fd413dee5 AvatarMenu::AvatarMenu()
[pid=484869][err] #6 0x559fd413a96f DbusAppmenu::Initialize()
[pid=484869][err] #7 0x559fd413ce06 DbusAppmenuRegistrar::InitializeMenu()
[pid=484869][err] #8 0x559fd413d613 DbusAppmenuRegistrar::OnNameOwnerChanged()
[pid=484869][err] #9 0x559fca50b581 base::internal::Invoker<>::Run()
[pid=484869][err] #10 0x559fcacee061 base::internal::Invoker<>::RunOnce()
[pid=484869][err] #11 0x559fce760bd4 base::TaskAnnotator::RunTaskImpl()
[pid=484869][err] #12 0x559fce779cc3 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
[pid=484869][err] #13 0x559fce779739 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=484869][err] #14 0x559fce77a195 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=484869][err] #15 0x559fce7e3314 base::MessagePumpGlib::Run()
[pid=484869][err] #16 0x559fce77a514 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
[pid=484869][err] #17 0x559fce741306 base::RunLoop::Run()
[pid=484869][err] #18 0x559fcc68d823 content::BrowserMainLoop::RunMainMessageLoop()
[pid=484869][err] #19 0x559fcc68f322 content::BrowserMainRunnerImpl::Run()
[pid=484869][err] #20 0x559fcc68ae96 content::BrowserMain()
[pid=484869][err] #21 0x559fcdbbb0a8 content::RunBrowserProcessMain()
[pid=484869][err] #22 0x559fcdbbc9f4 content::ContentMainRunnerImpl::RunBrowser()
[pid=484869][err] #23 0x559fcdbbc7e6 content::ContentMainRunnerImpl::Run()
[pid=484869][err] #24 0x559fcdbb9db0 content::RunContentProcess()
[pid=484869][err] #25 0x559fcdbb9fdd content::ContentMain()
[pid=484869][err] #26 0x559fca36730a ChromeMain
[pid=484869][err] #27 0x7fadc7223a90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x23a8f)
[pid=484869][err] #28 0x7fadc7223b49 __libc_start_main
[pid=484869][err] #29 0x559fca36702a _start
[pid=484869][err]   r8: 0000000000000000  r9: 00003e4001028b90 r10: 0000559fd52e1040 r11: 00007fadc61b0a18
[pid=484869][err]  r12: 0000559fd5221000 r13: 00003e4001028c70 r14: 00003e4001028c30 r15: 00003e4001028c48
[pid=484869][err]   di: 0000000000000148  si: 00003e4001028c30  bp: 00007ffc5fcb3cb0  bx: 0000000000000148
[pid=484869][err]   dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffc5fcb3c60
[pid=484869][err]   ip: 0000559fca518710 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
[pid=484869][err]  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000148
[pid=484869][err] [end of stack trace]
    at AtCoder.<anonymous> (/usr/local/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:250:58)
    at step (/usr/local/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:69:23)
    at Object.next (/usr/local/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:50:53)
    at fulfilled (/usr/local/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:41:58) {
  name: 'Error'
}

Node.js v20.5.1
```

I am not sure about how to obtain more useful information about this error, please let me know if any debug information is needed.

**Comment by searleser97** [comment]
Could you try downgrading your nodejs version to `16.x.x` ?

**Comment by searleser97** [comment]
wait i just noticed you installed with `npm install cpb -g` it should be `npm install cpbooster -g`

**Comment by fhvirus** [comment]
Using nodejs `v16.20.2` also gives similar error:
```
lemon:~/ $ cpb l atcoder                                                                                                                                                            [10:18:16]
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserContext.newPage: Browser closed.
==================== Browser output: ====================
<launching> /home/lemon/.cache/ms-playwright/chromium-1076/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-IgtXq9 --remote-debugging-pipe --no-startup-window
<launched> pid=12265
[pid=12265][err] 
[pid=12265][err] (chrome:12265): Gtk-WARNING **: 10:18:21.834: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name
[pid=12265][err] 
[pid=12265][err] (chrome:12265): Gtk-WARNING **: 10:18:21.834: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
[pid=12265][err] [12265:12265:0905/101821.909761:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.
[pid=12265][err] [0905/101822.144785:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=12265][err] [0905/101822.144970:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=12265][err] [0905/101822.145020:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=12265][err] [0905/101822.145071:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=12265][err] Received signal 11 SEGV_MAPERR 000000000148
[pid=12265][err] #0 0x5577dc978842 base::debug::CollectStackTrace()
[pid=12265][err] #1 0x5577dc965e23 base::debug::StackTrace::StackTrace()
[pid=12265][err] #2 0x5577dc9782d1 base::debug::(anonymous namespace)::StackDumpSignalHandler()
[pid=12265][err] #3 0x7fab7583c4b0 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x3c4af)
[pid=12265][err] #4 0x5577d86c0710 base::ObserverList<>::AddObserver()
[pid=12265][err] #5 0x5577e22e5ee5 AvatarMenu::AvatarMenu()
[pid=12265][err] #6 0x5577e22e296f DbusAppmenu::Initialize()
[pid=12265][err] #7 0x5577e22e4e06 DbusAppmenuRegistrar::InitializeMenu()
[pid=12265][err] #8 0x5577e22e5613 DbusAppmenuRegistrar::OnNameOwnerChanged()
[pid=12265][err] #9 0x5577d86b3581 base::internal::Invoker<>::Run()
[pid=12265][err] #10 0x5577d8e96061 base::internal::Invoker<>::RunOnce()
[pid=12265][err] #11 0x5577dc908bd4 base::TaskAnnotator::RunTaskImpl()
[pid=12265][err] #12 0x5577dc921cc3 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
[pid=12265][err] #13 0x5577dc921739 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=12265][err] #14 0x5577dc922195 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=12265][err] #15 0x5577dc98b314 base::MessagePumpGlib::Run()
[pid=12265][err] #16 0x5577dc922514 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
[pid=12265][err] #17 0x5577dc8e9306 base::RunLoop::Run()
[pid=12265][err] #18 0x5577da835823 content::BrowserMainLoop::RunMainMessageLoop()
[pid=12265][err] #19 0x5577da837322 content::BrowserMainRunnerImpl::Run()
[pid=12265][err] #20 0x5577da832e96 content::BrowserMain()
[pid=12265][err] #21 0x5577dbd630a8 content::RunBrowserProcessMain()
[pid=12265][err] #22 0x5577dbd649f4 content::ContentMainRunnerImpl::RunBrowser()
[pid=12265][err] #23 0x5577dbd647e6 content::ContentMainRunnerImpl::Run()
[pid=12265][err] #24 0x5577dbd61db0 content::RunContentProcess()
[pid=12265][err] #25 0x5577dbd61fdd content::ContentMain()
[pid=12265][err] #26 0x5577d850f30a ChromeMain
[pid=12265][err] #27 0x7fab75823a90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x23a8f)
[pid=12265][err] #28 0x7fab75823b49 __libc_start_main
[pid=12265][err] #29 0x5577d850f02a _start
[pid=12265][err]   r8: 0000000000000002  r9: 0000000000000000 r10: 00005577e3489040 r11: 00007fab7479da18
[pid=12265][err]  r12: 00005577e33c9000 r13: 00003d84010802c0 r14: 00003d8401080280 r15: 00003d8401080298
[pid=12265][err]   di: 0000000000000148  si: 00003d8401080280  bp: 00007ffeb72a1250  bx: 0000000000000148
[pid=12265][err]   dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffeb72a1200
[pid=12265][err]   ip: 00005577d86c0710 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
[pid=12265][err]  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000148
[pid=12265][err] [end of stack trace]
    at AtCoder.<anonymous> (/home/lemon/.nvm/versions/node/v16.20.2/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:250:58)
    at step (/home/lemon/.nvm/versions/node/v16.20.2/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:69:23)
    at Object.next (/home/lemon/.nvm/versions/node/v16.20.2/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:50:53)
    at fulfilled (/home/lemon/.nvm/versions/node/v16.20.2/lib/node_modules/cpbooster/dist/src/Submit/OnlineJudgeFactory/OnlineJudge.js:41:58) {
  name: 'Error'
}
```

And `npm install cpb -g` was a typo, I've fixed the previous comment.

**Comment by searleser97** [comment]
I believe this has to do with some updates in OS 🤔, could you try setting up a virtual machine with an stable version of Ubuntu without upgrading it after install

**Comment by fhvirus** [comment]
Using `cpb l atcoder` with Konsole on Ubuntu 22.04, Node 20.6.0, npm 9.8.1 works. I'll try to do more testing.

**Comment by fhvirus** [comment]
Downgraded my computer to Kubuntu 22.04 solved the problem. Still not sure what caused the error, but I'm never gonna upgrade to none-LTS version again.
